[package]
name = "rc_ex_5"
version = "0.1.0"
edition = "2021"

[lib]
path = "src/lib.rs"

[dependencies]
pin-project = "1.1"
thiserror = "1"
futures = "0.3"
tokio = { version = "1.43", features = ["rt-multi-thread", "macros", "sync", "time"] }
